name: Accessibility check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Build
        run: bundle exec jekyll build
      - name: Run Axe
        run: |
          npm install --global @axe-core/cli http-server
          http-server _site/ &
          axe http://localhost:8080/ http://localhost:8080/publications/ --load-delay=1000 --exit
